name: Create and use abc2svg build environment

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y fossil
      - run: fossil version
      - run: fossil clone https://chiselapp.com/user/moinejf/repository/abc2svg abc2svg.fossil
      - run: fossil open abc2svg.fossil
      - run: fossil pull
      - run: fossil update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save abc2svg repository and working files locally
