name: Create and use abc2svg build environment

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  abctopdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt install -y fossil
      - run: fossil version
      # Comment out `clone` and `open` if the repository already exists locally
#      - run: fossil clone https://chiselapp.com/user/moinejf/repository/abc2svg abc2svg.fossil
#      - run: fossil open abc2svg.fossil
      - run: fossil pull
      - run: fossil update

      - run: sudo apt install -y ninja-build
      - run: ninja -v
        env:
          NOMIN: 1

      - run: mkdir ${GITHUB_WORKSPACE}/out
      - run: chmod +x ${GITHUB_WORKSPACE}/abctopdf
      - run: sh ${GITHUB_WORKSPACE}/abctopdf ${GITHUB_WORKSPACE}/abc/agora.abc -o ${GITHUB_WORKSPACE}/out/agora.pdf

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save abc2svg repository and working files locally
