name: Create and use abc2svg build environment

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: sudo apt install -y fossil
      - run: fossil --version
