name: Convert ABC to PDF

# Controls when the workflow will run
on: workflow_dispatch

jobs:
  abctopdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: sudo apt-get update
      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: ghostscript
      - run: chmod +x converter/abcm2ps
      - run: mkdir -p out
      - run: |
          for abcfile in in/*.abc; do \
              echo ""; \
              [ -e "out/${abcfile##*/}.pdf" ] || continue; \
              converter/abcm2ps $abcfile; \
              ps2pdf ${abcfile##*/}.ps out/${abcfile##*/}.pdf; \
              rm ${abcfile##*/}.ps; \
          done

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Save generated PDF
